# SPDX-License-Identifier: MIT
# Copyright (C) 2026 VIKINGYFY
# iStore Edition for MediaTek Platform

name: MTK-ISTORE

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 6'  # 每周六凌晨2点自动编译

jobs:
  istore:
    name: iStore-NoWiFi
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_CONFIG: MEDIATEK-ISTORE-NO
      WRT_THEME: argon
      WRT_NAME: OWRT
      WRT_SSID: OWRT
      WRT_WORD: 12345678
      WRT_IP: 192.168.10.1
      WRT_PW: 无
      WRT_REPO: https://github.com/VIKINGYFY/immortalwrt.git
      WRT_BRANCH: owrt
      WRT_SOURCE: VIKINGYFY/immortalwrt
      WRT_PACKAGE: |
        # iStore 生态
        CONFIG_PACKAGE_luci-app-store=y
        CONFIG_PACKAGE_luci-app-quickstart=y
        CONFIG_PACKAGE_luci-app-istorex=y
        
        # OpenClash
        CONFIG_PACKAGE_luci-app-openclash=y
        
        # Docker
        CONFIG_PACKAGE_luci-app-dockerman=y
        
        # 磁盘管理
        CONFIG_PACKAGE_luci-app-diskman=y
        
        # 定时任务
        CONFIG_PACKAGE_luci-app-taskplan=y
        
        # 主题
        CONFIG_PACKAGE_luci-theme-argon=y
        CONFIG_PACKAGE_luci-app-argon-config=y
        CONFIG_PACKAGE_luci-theme-aurora=y
        CONFIG_PACKAGE_luci-app-aurora-config=y
